# Generated by Django 4.2.1 on 2023-05-28 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('type', models.CharField(choices=[('TR', 'Отвод'), ('TP', 'Тройник'), ('QP', 'Крестовина'), ('RQ', 'Редукция'), ('TB', 'Труба')], max_length=60)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('d_1', models.IntegerField()),
                ('d_2', models.IntegerField()),
                ('d_3', models.IntegerField()),
                ('angle', models.IntegerField()),
            ],
        ),
    ]
